version: "3.8"
services:

  search_test:
    image: elasticsearch:7.17.28
    container_name: es01_test
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - cluster.initial_master_nodes=es01
    tmpfs: /usr/share/elasticsearch/data
    expose:
      - "9200"
    ports:
      - "9201:9200"
    command: >
      bash -c "
        elasticsearch-plugin install --batch analysis-icu &&
        /usr/local/bin/docker-entrypoint.sh eswrapper
      "
