services:
  search_test:
    image: elasticsearch:7.17.28
    container_name: es01_test
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - cluster.initial_master_nodes=es01
      # try this if you run into error 137
      # - ES_JAVA_OPTS=-Xms750m -Xmx750m
    tmpfs: /usr/share/elasticsearch/data
    expose:
      - "9200"
    ports:
      - "9201:9200"
    command: >
      bash -c "
        if ! elasticsearch-plugin list | grep -q analysis-icu; then
          elasticsearch-plugin install --batch analysis-icu
        fi &&
        /usr/local/bin/docker-entrypoint.sh eswrapper
      "
