---
version: 2

jobs:
  build:
    docker:
      - image: udata/circleci:py3.11-bookworm
      - image: udata/elasticsearch:7.16.2
        environment:
          node.name: es01
          cluster.name: es-docker-cluster
          cluster.initial_master_nodes: es01
    environment:
       BASH_ENV: /root/.bashrc
    steps:
      - checkout
      - run:
          name: Get the base reference branch
          command: export BASE_BRANCH=$(base_branch)
      - restore_cache:
          keys:
            - py-cache-v1-{{ arch }}-{{ checksum "pyproject.toml" }}
            - py-cache-v1-{{ arch }}-{{ .Branch }}
            - py-cache-v1-{{ arch }}-{{ .Environment.BASE_BRANCH }}
      - run:
          name: Install python dependencies
          command: |
            virtualenv venv
            source venv/bin/activate
            make deps
      - save_cache:
          key: py-cache-v1-{{ arch }}-{{ checksum "pyproject.toml" }}
          paths:
            - venv
      - save_cache:
          key: py-cache-v1-{{ arch }}-{{ .Branch }}
          paths:
            - venv
      - run:
          name: Wait for elasticsearch
          command: dockerize -wait tcp://localhost:9200 -timeout 5m
      - run:
          name: Run tests
          environment:
            ELASTICSEARCH_URL_TEST: http://localhost:9200
          command: |
            source venv/bin/activate
            make test
      - run:
          name: Build a distributable package
          command: |
            source venv/bin/activate
            # Build a wheel release
            flit build
      - store_artifacts:
          path: dist
      - persist_to_workspace:
          root: .
          paths:
            - .

  publish:
    docker:
      - image: udata/circleci:py3.11-bookworm
    steps:
      - attach_workspace:
          at: .
      - deploy:
          name: Publish on PyPI
          command: |
            source venv/bin/activate
            FLIT_USERNAME=${PYPI_USERNAME} FLIT_PASSWORD=${PYPI_PASSWORD} make publish

workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            tags:
              only: /v[0-9]+(\.[0-9]+)*/
      - publish:
          requires:
            - build
          filters:
            branches:
              only:
                - main
                - /[0-9]+(\.[0-9]+)+/
            tags:
              only: /v[0-9]+(\.[0-9]+)*/
          context: org-global
