name: build and test

on: [push]

jobs:
    build:
        runs-on: ubuntu-latest
        services:
          es-1:
            image: udata/elasticsearch:7.16.2
            env:
              node.name: es01
              cluster.name: es-docker-cluster
              cluster.initial_master_nodes: es01
            ports:
              - 9201:9200
        strategy:
          matrix:
            python-version: [3.9]

        steps:
            - name: Checkout sources
              uses: actions/checkout@v2

            - name: Set up Python
              uses: actions/setup-python@v2
              with:
                  python-version: ${{ matrix.python-version }}

            - name: Install dependencies
              run: |
                make deps

            - name: Lint with flake8
              run: |
                make lint

            - name: Test with pytest
              run: |
                make test
